### ISSUE TITLE
Document cwd functionality

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-docs#37]
This functionality is addressed in [this hooks issue](https://github.com/nanobox-io/nanobox-hooks-code/issues/31).

The `cwd` allows users to specify the working directory in which a start command should run.

```yaml
web.main:
  cwd: some-dir
  start: start-command

web.api:
  start:
    start1: start-command1
    start2: start-command2
  cwd:
    start1: dir1
    start2: dir2
```

_@tylerflint, is this ^ the correct format for multiple start/cwd configs?_
